### ISSUE TITLE
Slides del ejemplo Práctico 

### ISSUE THREAD

**Issue by G00Z-G00Z** [Troyanos-Robotics-Club/documentation-obsidian#14]
Falta poner las slides del ejemplo práctico. Pero también necesitamos tener el ejemplo práctico terminado

**Comment by david-villanueva-02** [comment]
smn en eso ando trabajando, primero quiero hacer el código y después poner las slides.

**Comment by G00Z-G00Z** [comment]
Ya tienen el ejemplo funcional ?

**Comment by david-villanueva-02** [comment]
Sip
