### ISSUE TITLE
correcciones villa

### ISSUE THREAD

**Issue by david-villanueva-02** [Troyanos-Robotics-Club/documentation-obsidian#21]
cambiar el setup.py a cuando creamos el nodo
slide de publishers
Agregar link a std_msgs
ros2_pkg en lugar de ros2_ws en build nodo publisher

**Comment by david-villanueva-02** [comment]
Agregar ROS_DOMAIN_ID diferente a cada uno

**Comment by david-villanueva-02** [comment]
Quitar slide random

**Comment by G00Z-G00Z** [comment]
Falta lo de ROS ID No ?

**Comment by david-villanueva-02** [comment]
Lo explicaré durante el taller.
