### ISSUE TITLE
Overflow raro en última slide branch villa/taller-ros

### ISSUE THREAD

**Issue by david-villanueva-02** [Troyanos-Robotics-Club/documentation-obsidian#24]

**Comment by G00Z-G00Z** [comment]
Resulta que el redering the advanced slides busca html (E.g. \<div\>\</div\>). Por lo que cuando pones lo de `distancia < 10.0` se confunde porque "falta" el \>

**Comment by G00Z-G00Z** [comment]
Para solucionarlo, agregué el \> "Faltante" después del bloque de código. Que de hecho no aparece en la presentación
