### ISSUE TITLE
Estructura del ejemplo práctico

### ISSUE THREAD

**Issue by G00Z-G00Z** [Troyanos-Robotics-Club/documentation-obsidian#7]
Necesitamos tener la estructura del ejemplo que vamos a usar

08be9a2ffa590705fce472593fe0b4ee8efc441a en este commit agregué un dibujo preliminar. Hay que ponernos de acuerdo con los topics, pub y subs para ponerlos en la presentación

**Comment by david-villanueva-02** [comment]
Garza y yo teníamos esta idea:
Nodo en la RPi:
Controla los actuadores: LEDs y puerta con base en la info recibida de los subscribers. Manda info de los sensores: distancia del sensor de proximidad y estado del botón pulsado a los publishers.
Tendrá dos publishers:
publisher_proximidad: distancia del sensor recibido, tipo Int32 de std_msgs. Topic /distancia_sensor
publisher_boton: si el botón se encuentra presionado o no, tipo Bool de std_msgs. Topic /estado_boton

Tendrá dos subscribers:
subsciber_LED: recibirá información de si debe encender el LED o no. tipo Bool de std_msgs. Topic: /estado_LED
subscriber_servo: recibirá el duty cycle de la señal PWM para mandar al servo. Tipo Int32 de std_msgs. Topic /pwm_servo

Nodo en la VM (lo que harían los chavitos durante el taller):
NODO 1:
recibe la info del sensor de distancia y, con base en eso, enciende las luces LED. Puede ser un threshold para mandar la señal. O podemos poner que, si la distancia es mantiene constante, se apaga (simulando que no hay nadie moviéndose en el cuarto, por lo tanto no es necesario prender las luces)
publisher_LED: manda el estado del LED. Tipo Bool de std_msgs en topic /estado_LED
subscriber_proximidad: recibe la distancia del sensor recibido. Tipo Int32 de std_msgs en topuc /distancia_sensor

NODO 2:
recibe la info del botón y abre y cierra la puerta
subscriber_boton: recibe el estado del botón, tipo Bool de std_msgs en el topic /estado_boton
publisher_servo: manda el DC del PWM al servo, de tipo Int32 de std_msgs en topuc /pwm_servo

Qué opinan?

**Comment by david-villanueva-02** [comment]
![Uploading imagen_2023-11-02_221714792.png…]()

**Comment by david-villanueva-02** [comment]
![ejemplo_taller](https://github.com/Troyanos-Robotics-Club/documentation-obsidian/assets/139887285/fc869eb2-dea2-4af2-aba3-66842577d0e8)

**Comment by G00Z-G00Z** [comment]
Me parece muy bien la idea, solamente mi problema es con los **std_msgs**. Creen que sea momento para introducir esos mensajes ? Si es muy complicado, podemos dejarlo con tipos de variables simples


También sobre el ensamblado @david-villanueva-02 tu te vas a encargar de cablearlo ?

**Comment by david-villanueva-02** [comment]
Para los std_msgs este garza va a explicar en general qué son las interfaces y cómo crear una. std_msgs es una que ya viene incluida en ROS así que podemos tratarla como "tipos de variables simples". Como quiera según yo se necesita una interfaz para poder configurar los topics, así q en resumen no creo que sea tanto pedo. 

Y sí, si quieren yo hago el cableado y el nodo de la rpi y ya uds hagan una rama diferente para cada nodo diferente. Estos son los que correrían en la RPi y sería el resultado final de lo que harían en el curso. Ya cuando terminen me hacen el pull request y mezclo las ramas.

**Comment by G00Z-G00Z** [comment]
Tambien, para los servicios y clientes róbotica, que componente podríamos hacer ?

**Comment by david-villanueva-02** [comment]
Estabamos pensando garza y yo que puede que no sea 100% necesario, realmente con publishers y subscribers se arma, qué opinas?

**Comment by G00Z-G00Z** [comment]
Me parece bien, con pub y sub es más que suficiente. Entonces en la presentación los quito ? @davidogarzas @david-villanueva-02

**Comment by G00Z-G00Z** [comment]
Los voy a quitar
